USE MASTER
GO

IF EXISTS(SELECT * FROM SYS.databases WHERE NAME = 'Pizzaria')
BEGIN
    DROP DATABASE Pizzaria
END
GO

CREATE DATABASE Pizzaria
GO

USE Pizzaria
GO 

CREATE TABLE LOGIN
(
    ID INT IDENTITY PRIMARY KEY,
    USUARIO CHAR(8) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA CHAR(8) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
)

GO

CREATE TABLE CARGO 
(
    ID INT IDENTITY PRIMARY KEY,
    NOME_CARGO VARCHAR(100) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
) 
GO

CREATE TABLE CLIENTE 
(
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NULL,
    DATA_NASC DATE NULL,
    CEP CHAR(8) NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    NUM_RESID VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100) NULL,
    STATUS VARCHAR(10) NOT NULL,
    LOGIN_ID INT,

    FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN (ID)
)
GO

CREATE TABLE CATEGORIA_PRODUTO
(
    ID INT IDENTITY PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
)
GO

CREATE TABLE FUNCIONARIO 
(
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    CARGO_ID INT,
    LOGIN_ID INT,

    FOREIGN KEY (CARGO_ID) REFERENCES CARGO (ID),
    FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN (ID)
)
GO

CREATE TABLE SERVICO
(
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO DECIMAL (8,2) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
)
GO 

CREATE TABLE PRODUTO 
(
    ID INT IDENTITY PRIMARY KEY,
    NOME_PROD VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR (100) NOT NULL,
    TAMANHO VARCHAR(10) NOT NULL,
    PRECO DECIMAL(8,2) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    CATEGORIA_PRODUTO_ID INT NOT NULL,

    FOREIGN KEY (CATEGORIA_PRODUTO_ID) REFERENCES CATEGORIA_PRODUTO (ID)
)
GO

CREATE TABLE PEDIDO
(
    ID INT IDENTITY,
    CLIENTE_ID INT NOT NULL,
    FUNCIONARIO_ID INT NOT NULL,
    SERVICO_ID INT NOT NULL,
    CUPOM_ID INT NULL,
    PRECO DECIMAL(8,2) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID),
    FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID),
    FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO (ID),
    FOREIGN KEY (CUPOM_ID) REFERENCES CUPOM (ID)
)
GO

CREATE TABLE PEDIDO_ITEM
(
    ID INT IDENTITY,
    PEDIDO_ID INT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    TAMANHO VARCHAR(10) NOT NULL,
    QTD INT NOT NULL,
    DESCRICAO VARCHAR(100) NULL,
    STATUS VARCHAR(10) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID)
)
GO

CREATE TABLE CUPOM 
(
    ID INT IDENTITY,
    NUMERO_CUPOM VARCHAR(6) NOT NULL,
    DATA_GERADO SMALLDATETIME NOT NULL,
    DATA_VALIDADE DATETIME NOT NULL,
    DATA_USO DATETIME NULL,
    VALOR DECIMAL(8,2) NOT NULL,
    CLIENTE_ID INT NOT NULL,
    STATUS VARCHAR(10) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
)
GO

CREATE TABLE FORMA_PAGAMENTO 
(
    ID INT IDENTITY,
    NOME_PAGAMENTO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(15) NOT NULL,
    CUPOM_ID INT NULL,
    STATUS VARCHAR(10) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (CUPOM_ID) REFERENCES CUPOM (ID)
)












